

.PHONY: keyscape melisma homophony

all:	keyscape melisma homophony syllable


keyscape:
	(cd keyscape; make)


melisma:
	(cd melisma; make)


homophony:
	(cd homophony; make)

syllable:
	(cd syllable; make)
	
