

.PHONY: keyscape melisma homorhythm

all:	keyscape melisma homorhythm syllable


keyscape:
	(cd keyscape; make)


melisma:
	(cd melisma; make)


homorhythm:
	(cd homorhythm; make)


syllable:
	(cd syllable; make)
	
